import { useState } from 'react'
import Modal from '../ui/Modal'
import Button from '../ui/Button'
import { adminApi } from '../../services/api'

// "Reset password" for the admin console, shared by the All Users, Job Seekers
// and Employers tables so the behaviour and the wording of a security-relevant
// action cannot drift between them.
//
// The temporary password is generated by the server and displayed exactly
// once. There is no "show it again" — that is deliberate, and it is why the
// confirmation before resetting is explicit about what happens to the account
// (every session ends, and the user must choose a new password at next sign-in).
export default function ResetPasswordButton({ user, onDone, variant = 'icon' }) {
  const [isOpen, setIsOpen] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)
  const [issued, setIssued] = useState(null)
  const [copied, setCopied] = useState(false)

  const reset = async () => {
    setBusy(true)
    setError(null)
    try {
      const res = await adminApi.resetUserPassword(user.id)
      setIssued(res)
      setCopied(false)
      onDone?.(user, res)
    } catch (err) {
      // Shown inside the dialog rather than swallowed: a reset that appears to
      // have worked when the mail send failed would leave the admin thinking
      // the user has the password when they have not.
      setError(err?.message || 'Could not reset this password. Please try again.')
    } finally {
      setBusy(false)
    }
  }

  const copyPassword = async () => {
    if (!issued?.temporary_password) return
    try {
      await navigator.clipboard.writeText(issued.temporary_password)
      setCopied(true)
    } catch {
      // Clipboard access is denied in some browsers and over plain HTTP. The
      // password is on screen either way, so this is a convenience only.
      setCopied(false)
    }
  }

  const close = () => {
    setIsOpen(false)
    setIssued(null)
    setError(null)
    setCopied(false)
  }

  const label = `Reset password for ${user.name}`

  return (
    <>
      {variant === 'icon' ? (
        <button
          type="button"
          className="hh-icon-btn"
          data-tooltip="Reset password"
          aria-label={label}
          onClick={() => setIsOpen(true)}
        >
          <i className="bi bi-key" aria-hidden="true" />
        </button>
      ) : (
        <Button variant="ghost" onClick={() => setIsOpen(true)}>
          <i className="bi bi-key me-2" aria-hidden="true" />
          Reset password
        </Button>
      )}

      <Modal
        isOpen={isOpen}
        onClose={busy ? undefined : close}
        title={issued ? 'Temporary password issued' : `Reset ${user.name}'s password?`}
        size="sm"
        footer={
          issued ? (
            <Button variant="primary" onClick={close}>
              Done
            </Button>
          ) : (
            <>
              <Button variant="ghost" onClick={close} disabled={busy}>
                Cancel
              </Button>
              <Button variant="primary" onClick={reset} disabled={busy}>
                {busy ? 'Resetting…' : 'Reset password'}
              </Button>
            </>
          )
        }
      >
        {issued ? (
          <>
            <p className="mb-3">
              Send this to <strong>{user.name}</strong> over a channel you trust. It is
              shown only once — once you close this dialog it cannot be retrieved.
            </p>

            <div className="d-flex align-items-center gap-2 mb-3">
              <code className="flex-grow-1 text-break hh-temp-password">{issued.temporary_password}</code>
              <Button variant="outline-primary" onClick={copyPassword} className="flex-shrink-0">
                {copied ? 'Copied' : 'Copy'}
              </Button>
            </div>

            <ul className="small text-secondary mb-0 hh-pl-4">
              <li>They must choose a new password the next time they sign in.</li>
              <li>Every existing session has been signed out.</li>
              <li>
                {issued.notification_sent
                  ? 'They were also emailed a link to reset it themselves.'
                  : 'The email could not be sent, so pass the password on yourself.'}
              </li>
            </ul>
          </>
        ) : (
          <>
            <p className="mb-0 text-secondary">
              A temporary password will be generated for{' '}
              <strong>{user.name}</strong>. They will be signed out everywhere and
              required to choose a new password at their next sign-in.
            </p>
            {error ? (
              <div className="alert alert-danger mt-3 mb-0" role="alert">
                {error}
              </div>
            ) : null}
          </>
        )}
      </Modal>
    </>
  )
}